version: "3.1"

services:
  server:
    build: .
    container_name: degg-sbox
    command: npm run dev
    working_dir: /opt/app-root
    volumes:
      - ./:/opt/app-root
      - /usr/app/node_modules
    ports:
      - "8080:8080"
      - "8443:8443"
    depends_on:
      - database
  database:
    image: postgres:14.1
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGPORT=${POSTGRES_PORT}
