version: "3.1"

services:
  server:
    build: .
    container_name: degg-sbox
    working_dir: /opt/app-root
    volumes:
      - ./src:/opt/app-root/src
      - .env:/opt/app-root/.env
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
      - "8443:8443"
