on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Build Application

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Build, tag, and push the image to Amazon ECR
        id: build-image
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_ACCESS_SECRET: ${{ secrets.AWS_ACCESS_KEY_ID }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: degg-sbox
          IMAGE_TAG: ${{ github.sha }}
        run:
          aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 475144453288.dkr.ecr.ap-southeast-2.amazonaws.com
          docker build -t degg-sbox .
          docker tag degg-sbox:latest 475144453288.dkr.ecr.ap-southeast-2.amazonaws.com/degg-sbox:latest
          docker push 475144453288.dkr.ecr.ap-southeast-2.amazonaws.com/degg-sbox:latest
